/** Centralized query key factory — keeps cache keys consistent and typo-free. */
export const queryKeys = {
  session: ["auth", "session"] as const,
  incidentSummary: ["incidents", "summary"] as const,
  incidentList: ["incidents", "list"] as const,
  incidentDetail: (id: string) => ["incidents", "detail", id] as const,
  incidentsByIds: (ids: string[]) => ["incidents", "by-ids", ...ids] as const,
  alertSummary: ["alerts", "summary"] as const,
  alertList: ["alerts", "list"] as const,
  alertDetail: (id: string) => ["alerts", "detail", id] as const,
  orgRiskScore: ["threat", "risk-score"] as const,
  riskScore: (id: string) => ["threat", "risk-score", id] as const,
  activityTimeline: ["threat", "activity-timeline"] as const,
  topIndicators: ["threat", "top-indicators"] as const,
  topTechniques: ["threat", "top-techniques"] as const,
  systemHealth: ["threat", "system-health"] as const,
  incidentAnalysis: (id: string) => ["ai", "analysis", id] as const,
  incidentRecommendations: (id: string) => ["ai", "recommendations", id] as const,
  userList: ["users", "list"] as const,
  userDetail: (id: string) => ["users", "detail", id] as const,
  organization: ["users", "organization"] as const,
  indicatorsByIds: (ids: string[]) => ["threat", "indicators-by-ids", ...ids] as const,
  techniquesByIds: (ids: string[]) => ["threat", "techniques-by-ids", ...ids] as const,
  auditForResource: (resourceId: string) => ["audit", "resource", resourceId] as const,
  auditByActor: (actorId: string) => ["audit", "actor", actorId] as const,
  iocList: ["ioc", "list"] as const,
  iocDetail: (id: string) => ["ioc", "detail", id] as const,
  graph: ["threat", "graph"] as const,
  mitreTactics: ["mitre", "tactics"] as const,
  mitreTechniqueList: ["mitre", "techniques", "list"] as const,
  mitreTechniqueDetail: (id: string) => ["mitre", "techniques", "detail", id] as const,
  investigationList: ["investigations", "list"] as const,
  investigationDetail: (id: string) => ["investigations", "detail", id] as const,
  reportList: ["reports", "list"] as const,
  reportDetail: (id: string) => ["reports", "detail", id] as const,
  auditList: ["audit", "list"] as const,
};
