import type { InMemoryAlertRepository } from "./alert.repository.js";
import type { Alert } from "../types/alert.js";

/** Mirrors the frontend's src/mocks/alerts.ts (same IDs/content). */
export function seedDemoAlerts(repository: InMemoryAlertRepository): void {
  const organizationId = "org_northwind";

  const alerts: Alert[] = [
    {
      id: "alert_1",
      organizationId,
      title: "Multiple failed MFA challenges for finance account",
      description: "5 consecutive MFA denials for a finance-department account within 3 minutes.",
      severity: "high",
      confidence: "medium",
      status: "investigating",
      source: "Identity Provider",
      affectedAssets: ["sso-gateway"],
      relatedIndicatorIds: [],
      relatedIncidentId: "inc_1",
      createdAt: "2026-08-15T09:05:00Z",
    },
    {
      id: "alert_2",
      organizationId,
      title: "Endpoint protection quarantine event",
      description: "Loader family binary quarantined on ws-fin-014 before execution completed.",
      severity: "high",
      confidence: "confirmed",
      status: "resolved",
      source: "Endpoint Protection",
      affectedAssets: ["ws-fin-014"],
      relatedIndicatorIds: ["ind_9"],
      relatedIncidentId: "inc_2",
      createdAt: "2026-08-14T21:41:00Z",
    },
    {
      id: "alert_3",
      organizationId,
      title: "Rate-limit threshold exceeded on SSO gateway",
      description: "Failed authentication rate exceeded 200 attempts / 5 minutes from a single source.",
      severity: "critical",
      confidence: "high",
      status: "resolved",
      source: "SSO Gateway",
      affectedAssets: ["sso-gateway"],
      relatedIndicatorIds: ["ind_1"],
      relatedIncidentId: "inc_3",
      createdAt: "2026-08-15T10:40:00Z",
    },
    {
      id: "alert_4",
      organizationId,
      title: "Unusual outbound data volume",
      description: "410MB outbound transfer flagged as anomalous relative to host baseline.",
      severity: "critical",
      confidence: "high",
      status: "investigating",
      source: "Network IDS",
      affectedAssets: ["ws-fin-021"],
      relatedIndicatorIds: ["ind_3", "ind_7"],
      createdAt: "2026-08-15T03:40:00Z",
    },
    {
      id: "alert_5",
      organizationId,
      title: "New sign-in from unfamiliar region",
      description: "Successful sign-in from a region not previously observed for this account.",
      severity: "medium",
      confidence: "medium",
      status: "open",
      source: "Identity Provider",
      affectedAssets: [],
      relatedIndicatorIds: [],
      createdAt: "2026-08-15T09:55:00Z",
    },
    {
      id: "alert_6",
      organizationId,
      title: "Service account authenticated outside normal hours",
      description: "Shared service account authenticated to 3 hosts at 03:12 local time.",
      severity: "medium",
      confidence: "medium",
      status: "open",
      source: "SIEM Correlation",
      affectedAssets: ["ws-ops-004", "ws-ops-007", "file-server-2"],
      relatedIndicatorIds: [],
      createdAt: "2026-08-12T03:20:00Z",
    },
    {
      id: "alert_7",
      organizationId,
      title: "DNS query to newly registered domain",
      description: "Workstation resolved a domain registered within the last 14 days.",
      severity: "low",
      confidence: "low",
      status: "closed",
      source: "DNS Monitor",
      affectedAssets: ["ws-mkt-009"],
      relatedIndicatorIds: ["ind_4"],
      createdAt: "2026-08-11T13:00:00Z",
    },
    {
      id: "alert_8",
      organizationId,
      title: "Outdated TLS configuration detected",
      description: "Legacy TLS 1.0 handshake observed from an internal service.",
      severity: "info",
      confidence: "confirmed",
      status: "open",
      source: "Vulnerability Scanner",
      affectedAssets: ["legacy-reporting-svc"],
      relatedIndicatorIds: [],
      createdAt: "2026-08-10T06:00:00Z",
    },
  ];

  for (const alert of alerts) repository.seed(alert);
}
