import type { Report } from "@/types";
import { REPORT_TYPE_CONFIG } from "@/constants/reportType";
import { formatDate, formatDateTime } from "@/utils/format";

/**
 * Client-side export — no backend involved. A real deployment might also
 * offer a server-rendered PDF, but a Markdown download is a genuine,
 * fully-functional capability achievable entirely in the browser.
 */
export function downloadReportAsMarkdown(report: Report, bodyLines: string[] = []) {
  const lines = [
    `# ${report.title}`,
    "",
    `**Type:** ${REPORT_TYPE_CONFIG[report.type].label}`,
    `**Period:** ${formatDate(report.periodStart)} – ${formatDate(report.periodEnd)}`,
    `**Generated by:** ${report.generatedBy} on ${formatDateTime(report.generatedAt)}`,
    "",
    "## Summary",
    "",
    report.summary,
    ...bodyLines,
  ];

  const blob = new Blob([lines.join("\n")], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = `${report.id}.md`;
  document.body.appendChild(anchor);
  anchor.click();
  document.body.removeChild(anchor);
  URL.revokeObjectURL(url);
}
