import { useState } from "react";
import { useNavigate } from "react-router-dom";
import type { Report, ReportType } from "@/types";
import { useReportsList } from "@/api/useReports";
import { PageHeader } from "@/components/PageHeader";
import { Input } from "@/components/Input";
import { Select } from "@/components/Select";
import { Table, type TableColumn } from "@/components/Table";
import { Pagination } from "@/components/Pagination";
import { Icon } from "@/components/Icon";
import { Button } from "@/components/Button";
import { usePermission } from "@/hooks/usePermission";
import { REPORT_TYPE_CONFIG, REPORT_TYPE_ORDER } from "@/constants/reportType";
import { formatDate, formatRelativeTime } from "@/utils/format";
import { GenerateReportModal } from "./GenerateReportModal";
import styles from "./ReportsList.module.css";

const PAGE_SIZE = 10;

export function ReportsList() {
  const navigate = useNavigate();
  const canGenerate = usePermission("reports:generate");
  const [page, setPage] = useState(1);
  const [search, setSearch] = useState("");
  const [type, setType] = useState<ReportType | "all">("all");
  const [generateOpen, setGenerateOpen] = useState(false);

  const { data, isLoading, isError } = useReportsList({
    page,
    pageSize: PAGE_SIZE,
    search: search || undefined,
    type: type === "all" ? undefined : type,
  });

  const columns: TableColumn<Report>[] = [
    {
      key: "type",
      header: "Type",
      width: "200px",
      render: (row) => (
        <span className={styles.typeCell}>
          <Icon name={REPORT_TYPE_CONFIG[row.type].icon} size="sm" />
          {REPORT_TYPE_CONFIG[row.type].label}
        </span>
      ),
    },
    { key: "title", header: "Title", render: (row) => <span className={styles.titleCell}>{row.title}</span> },
    {
      key: "period",
      header: "Period",
      render: (row) => `${formatDate(row.periodStart)} – ${formatDate(row.periodEnd)}`,
    },
    { key: "generatedBy", header: "Generated by", render: (row) => row.generatedBy },
    {
      key: "generatedAt",
      header: "Generated",
      align: "right",
      render: (row) => <span className={styles.timestamp}>{formatRelativeTime(row.generatedAt)}</span>,
    },
  ];

  return (
    <div className={styles.root}>
      <PageHeader
        title="Reports"
        subtitle="Security summaries, incident reports, and risk digests generated from this workspace's data."
        actions={
          canGenerate && (
            <Button iconLeft="plus" onClick={() => setGenerateOpen(true)}>
              Generate report
            </Button>
          )
        }
      />

      <div className={styles.toolbar}>
        <div className={styles.search}>
          <Input
            label="Search reports"
            hideLabel
            iconLeft="magnifying-glass"
            placeholder="Search reports…"
            value={search}
            onChange={(e) => {
              setSearch(e.target.value);
              setPage(1);
            }}
          />
        </div>
        <div className={styles.filter}>
          <Select
            label="Filter by report type"
            hideLabel
            value={type}
            onChange={(e) => {
              setType(e.target.value as ReportType | "all");
              setPage(1);
            }}
            options={[
              { value: "all", label: "All types" },
              ...REPORT_TYPE_ORDER.map((t) => ({ value: t, label: REPORT_TYPE_CONFIG[t].label })),
            ]}
          />
        </div>
      </div>

      <Table
        columns={columns}
        data={data?.items ?? []}
        getRowId={(row) => row.id}
        loading={isLoading}
        onRowClick={(row) => navigate(`/app/reports/${row.id}`)}
        emptyIcon="file-lines"
        emptyTitle={isError ? "Couldn't load reports" : "No reports match these filters"}
        emptyDescription={
          isError
            ? "Something went wrong fetching reports. Try again in a moment."
            : "Try adjusting your search or filters, or generate a new report."
        }
      />

      {data && data.total > 0 && (
        <Pagination page={page} pageSize={PAGE_SIZE} total={data.total} onPageChange={setPage} />
      )}

      <GenerateReportModal
        open={generateOpen}
        onClose={() => setGenerateOpen(false)}
        onGenerated={(id) => navigate(`/app/reports/${id}`)}
      />
    </div>
  );
}
