import { Card } from "@/components/Card";
import { Icon } from "@/components/Icon";
import { Button } from "@/components/Button";
import { REPORT_TYPE_CONFIG } from "@/constants/reportType";
import { formatDate, formatDateTime } from "@/utils/format";
import { downloadReportAsMarkdown } from "../exportReport";
import type { Report } from "@/types";
import styles from "./ReportHeaderCard.module.css";

export function ReportHeaderCard({ report }: { report: Report }) {
  const config = REPORT_TYPE_CONFIG[report.type];

  return (
    <Card>
      <div className={styles.top}>
        <span className={styles.typeBadge}>
          <Icon name={config.icon} size="sm" />
          {config.label}
        </span>
        <div className={styles.actions}>
          <Button variant="secondary" size="sm" iconLeft="download" onClick={() => downloadReportAsMarkdown(report)}>
            Export
          </Button>
          <Button variant="secondary" size="sm" iconLeft="print" onClick={() => window.print()}>
            Print
          </Button>
        </div>
      </div>

      <h1 className={styles.title}>{report.title}</h1>
      <p className={styles.summary}>{report.summary}</p>

      <div className={styles.footer}>
        <span>
          Period {formatDate(report.periodStart)} – {formatDate(report.periodEnd)}
        </span>
        <span>
          Generated by {report.generatedBy} on {formatDateTime(report.generatedAt)}
        </span>
      </div>
    </Card>
  );
}
